Repository VictorHarri-Chal/AREA, pull requests merged in 2023-03, with the labels that each got.

#250 243 dropdown data for GitHub
  server/server.js
  server/src/controllers/github.controller.js
  server/src/services/actions/githubActions.js
  server/src/services/actions/twitch/twitchActions.js
  server/src/services/actions/youtube/youtubeActions.js
  web/src/components/AppSidebar/ASData.js
  web/src/components/Playground/index.js
Labels: enhancement

#274 [ADD] download apk
  web/src/components/HeroSection/HeroElements.js
  web/src/components/InfoSection/Data.js
  web/src/components/InfoSection/index.js
  web/src/components/Navbar/index.js
  web/src/components/PupSidebarR/index.js
  web/src/pages/Home/index.js
Labels: enhancement

#276 239 twitter api
  server/package-lock.json
  server/package.json
  server/server.js
  server/src/controllers/twitter.controller.js
  server/src/routes/services.routes.js
  server/src/services/actions/github/githubActions.js
  server/src/services/actions/twitter/twitterActions.js
  server/src/services/services.js
  web/src/components/AppSidebar/ASData.js
  web/src/components/BlocSidebar/HandleConnect.js
Labels: bug

#281 [UPD] about.json
  server/src/controllers/user.controller.js
Labels: documentation
